[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana = "3G6TYRGE6JX4BZPdeix4L38VtbrAUMWyK1yJ5DQoRc7c"

[programs.localnet]
solana = "3G6TYRGE6JX4BZPdeix4L38VtbrAUMWyK1yJ5DQoRc7c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/trump-fun.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
create_token = "pnpm exec ts-mocha -p ./tsconfig.json -t 10000 tests/create-token.ts"