[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana = "B2P5B5xVyuYPjvjz8s6CuDmHqQPj4mevrJ1gj5Yu1Fmb"

[programs.localnet]
solana = "B2P5B5xVyuYPjvjz8s6CuDmHqQPj4mevrJ1gj5Yu1Fmb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/trump-fun.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
