// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from 'as-proto/assembly';

export class ClaimPayout_Instruction {
  static encode(message: ClaimPayout_Instruction, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    writer.uint32(18);
    writer.string(message.acctBettingPools);

    writer.uint32(26);
    writer.string(message.acctPool);

    writer.uint32(34);
    writer.string(message.acctBet);

    writer.uint32(42);
    writer.string(message.acctBettor);

    writer.uint32(50);
    writer.string(message.acctBettorTokenAccount);

    writer.uint32(58);
    writer.string(message.acctProgramTokenAccount);
  }

  static decode(reader: Reader, length: i32): ClaimPayout_Instruction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ClaimPayout_Instruction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.acctBettingPools = reader.string();
          break;

        case 3:
          message.acctPool = reader.string();
          break;

        case 4:
          message.acctBet = reader.string();
          break;

        case 5:
          message.acctBettor = reader.string();
          break;

        case 6:
          message.acctBettorTokenAccount = reader.string();
          break;

        case 7:
          message.acctProgramTokenAccount = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  acctBettingPools: string;
  acctPool: string;
  acctBet: string;
  acctBettor: string;
  acctBettorTokenAccount: string;
  acctProgramTokenAccount: string;

  constructor(
    trxHash: string = '',
    acctBettingPools: string = '',
    acctPool: string = '',
    acctBet: string = '',
    acctBettor: string = '',
    acctBettorTokenAccount: string = '',
    acctProgramTokenAccount: string = ''
  ) {
    this.trxHash = trxHash;
    this.acctBettingPools = acctBettingPools;
    this.acctPool = acctPool;
    this.acctBet = acctBet;
    this.acctBettor = acctBettor;
    this.acctBettorTokenAccount = acctBettorTokenAccount;
    this.acctProgramTokenAccount = acctProgramTokenAccount;
  }
}
