// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from 'as-proto/assembly';

export class CreatePool_Instruction {
  static encode(message: CreatePool_Instruction, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    writer.uint32(18);
    writer.string(message.question);

    const options = message.options;
    if (options.length !== 0) {
      for (let i: i32 = 0; i < options.length; ++i) {
        writer.uint32(26);
        writer.string(options[i]);
      }
    }

    writer.uint32(32);
    writer.int64(message.betsCloseAt);

    writer.uint32(42);
    writer.string(message.originalTruthSocialPostId);

    writer.uint32(50);
    writer.string(message.imageUrl);

    writer.uint32(58);
    writer.string(message.acctBettingPools);

    writer.uint32(66);
    writer.string(message.acctPool);

    writer.uint32(74);
    writer.string(message.acctAuthority);
  }

  static decode(reader: Reader, length: i32): CreatePool_Instruction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CreatePool_Instruction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.question = reader.string();
          break;

        case 3:
          message.options.push(reader.string());
          break;

        case 4:
          message.betsCloseAt = reader.int64();
          break;

        case 5:
          message.originalTruthSocialPostId = reader.string();
          break;

        case 6:
          message.imageUrl = reader.string();
          break;

        case 7:
          message.acctBettingPools = reader.string();
          break;

        case 8:
          message.acctPool = reader.string();
          break;

        case 9:
          message.acctAuthority = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  question: string;
  options: Array<string>;
  betsCloseAt: i64;
  originalTruthSocialPostId: string;
  imageUrl: string;
  acctBettingPools: string;
  acctPool: string;
  acctAuthority: string;

  constructor(
    trxHash: string = '',
    question: string = '',
    options: Array<string> = [],
    betsCloseAt: i64 = 0,
    originalTruthSocialPostId: string = '',
    imageUrl: string = '',
    acctBettingPools: string = '',
    acctPool: string = '',
    acctAuthority: string = ''
  ) {
    this.trxHash = trxHash;
    this.question = question;
    this.options = options;
    this.betsCloseAt = betsCloseAt;
    this.originalTruthSocialPostId = originalTruthSocialPostId;
    this.imageUrl = imageUrl;
    this.acctBettingPools = acctBettingPools;
    this.acctPool = acctPool;
    this.acctAuthority = acctAuthority;
  }
}
