// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from 'as-proto/assembly';

export class Initialize_Instruction {
  static encode(message: Initialize_Instruction, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    writer.uint32(18);
    writer.string(message.usdcMint);

    writer.uint32(26);
    writer.string(message.freedomMint);

    writer.uint32(34);
    writer.string(message.acctBettingPools);

    writer.uint32(42);
    writer.string(message.acctAuthority);
  }

  static decode(reader: Reader, length: i32): Initialize_Instruction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Initialize_Instruction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.usdcMint = reader.string();
          break;

        case 3:
          message.freedomMint = reader.string();
          break;

        case 4:
          message.acctBettingPools = reader.string();
          break;

        case 5:
          message.acctAuthority = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  usdcMint: string;
  freedomMint: string;
  acctBettingPools: string;
  acctAuthority: string;

  constructor(
    trxHash: string = '',
    usdcMint: string = '',
    freedomMint: string = '',
    acctBettingPools: string = '',
    acctAuthority: string = ''
  ) {
    this.trxHash = trxHash;
    this.usdcMint = usdcMint;
    this.freedomMint = freedomMint;
    this.acctBettingPools = acctBettingPools;
    this.acctAuthority = acctAuthority;
  }
}
