// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from 'as-proto/assembly';
import { TokenTypeEnum } from './TokenTypeEnum';

export class PlaceBet_Instruction {
  static encode(message: PlaceBet_Instruction, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    writer.uint32(16);
    writer.uint64(message.optionIndex);

    writer.uint32(24);
    writer.uint64(message.amount);

    writer.uint32(32);
    writer.int32(message.tokenType);

    writer.uint32(42);
    writer.string(message.acctBettingPools);

    writer.uint32(50);
    writer.string(message.acctPool);

    writer.uint32(58);
    writer.string(message.acctBet);

    writer.uint32(66);
    writer.string(message.acctBettor);

    writer.uint32(74);
    writer.string(message.acctBettorTokenAccount);

    writer.uint32(82);
    writer.string(message.acctProgramTokenAccount);
  }

  static decode(reader: Reader, length: i32): PlaceBet_Instruction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PlaceBet_Instruction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.optionIndex = reader.uint64();
          break;

        case 3:
          message.amount = reader.uint64();
          break;

        case 4:
          message.tokenType = reader.int32();
          break;

        case 5:
          message.acctBettingPools = reader.string();
          break;

        case 6:
          message.acctPool = reader.string();
          break;

        case 7:
          message.acctBet = reader.string();
          break;

        case 8:
          message.acctBettor = reader.string();
          break;

        case 9:
          message.acctBettorTokenAccount = reader.string();
          break;

        case 10:
          message.acctProgramTokenAccount = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  optionIndex: u64;
  amount: u64;
  tokenType: TokenTypeEnum;
  acctBettingPools: string;
  acctPool: string;
  acctBet: string;
  acctBettor: string;
  acctBettorTokenAccount: string;
  acctProgramTokenAccount: string;

  constructor(
    trxHash: string = '',
    optionIndex: u64 = 0,
    amount: u64 = 0,
    tokenType: TokenTypeEnum = 0,
    acctBettingPools: string = '',
    acctPool: string = '',
    acctBet: string = '',
    acctBettor: string = '',
    acctBettorTokenAccount: string = '',
    acctProgramTokenAccount: string = ''
  ) {
    this.trxHash = trxHash;
    this.optionIndex = optionIndex;
    this.amount = amount;
    this.tokenType = tokenType;
    this.acctBettingPools = acctBettingPools;
    this.acctPool = acctPool;
    this.acctBet = acctBet;
    this.acctBettor = acctBettor;
    this.acctBettorTokenAccount = acctBettorTokenAccount;
    this.acctProgramTokenAccount = acctProgramTokenAccount;
  }
}
