// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from 'as-proto/assembly';

export class PoolImageSet_Event {
  static encode(message: PoolImageSet_Event, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    writer.uint32(16);
    writer.uint64(message.poolId);

    writer.uint32(26);
    writer.string(message.imageUrl);
  }

  static decode(reader: Reader, length: i32): PoolImageSet_Event {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PoolImageSet_Event();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.poolId = reader.uint64();
          break;

        case 3:
          message.imageUrl = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  poolId: u64;
  imageUrl: string;

  constructor(trxHash: string = '', poolId: u64 = 0, imageUrl: string = '') {
    this.trxHash = trxHash;
    this.poolId = poolId;
    this.imageUrl = imageUrl;
  }
}
