// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from 'as-proto/assembly';

export class PoolCreated_Event {
  static encode(message: PoolCreated_Event, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    writer.uint32(16);
    writer.uint64(message.poolId);

    writer.uint32(26);
    writer.string(message.question);

    const options = message.options;
    if (options.length !== 0) {
      for (let i: i32 = 0; i < options.length; ++i) {
        writer.uint32(34);
        writer.string(options[i]);
      }
    }

    writer.uint32(40);
    writer.int64(message.betsCloseAt);

    writer.uint32(50);
    writer.string(message.originalTruthSocialPostId);

    writer.uint32(58);
    writer.string(message.imageUrl);

    writer.uint32(64);
    writer.int64(message.createdAt);
  }

  static decode(reader: Reader, length: i32): PoolCreated_Event {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new PoolCreated_Event();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.poolId = reader.uint64();
          break;

        case 3:
          message.question = reader.string();
          break;

        case 4:
          message.options.push(reader.string());
          break;

        case 5:
          message.betsCloseAt = reader.int64();
          break;

        case 6:
          message.originalTruthSocialPostId = reader.string();
          break;

        case 7:
          message.imageUrl = reader.string();
          break;

        case 8:
          message.createdAt = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  poolId: u64;
  question: string;
  options: Array<string>;
  betsCloseAt: i64;
  originalTruthSocialPostId: string;
  imageUrl: string;
  createdAt: i64;

  constructor(
    trxHash: string = '',
    poolId: u64 = 0,
    question: string = '',
    options: Array<string> = [],
    betsCloseAt: i64 = 0,
    originalTruthSocialPostId: string = '',
    imageUrl: string = '',
    createdAt: i64 = 0
  ) {
    this.trxHash = trxHash;
    this.poolId = poolId;
    this.question = question;
    this.options = options;
    this.betsCloseAt = betsCloseAt;
    this.originalTruthSocialPostId = originalTruthSocialPostId;
    this.imageUrl = imageUrl;
    this.createdAt = createdAt;
  }
}
