[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.29"
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
via_ir = true

remappings = [
    "@account-abstraction/contracts=lib/account-abstraction/contracts/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"



[etherscan]
base-sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
